networks:
  fullstack:

volumes:
  mysql: ~
  shared_composer:
    external: true
  shared_pnpm:
    external: true


services:
  proxy:
    image: nginx:1.29.0-alpine3.22
    depends_on:
      - jsonserver
    networks:
      - fullstack
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro

  frontend:
     image: idomi27/vue:26
     build:
       context: ./frontend
       dockerfile: Dockerfile
     volumes:
       - ./frontend:/app:rw
       - shared_pnpm:/shared_pnpm
     networks:
       - fullstack

  jsonserver:
    image: idomi27/json-server:26
    build:
      context: ./jsonserver
      dockerfile: Dockerfile
    networks:
      - fullstack
    volumes:
      - ./jsonserver:/app
      - /app/node_modules
